### ISSUE TITLE
url broken

### ISSUE THREAD

**Issue by tianheg** [crimx/saladict.crimx.com#15]
source: https://github.com/crimx/saladict.crimx.com/blob/master/source/q&a.md?plain=1#L74

web: [问：能否让用户自定义添加词典。](https://saladict.crimx.com/q&a.html#%E9%97%AE%EF%BC%9A%E8%83%BD%E5%90%A6%E8%AE%A9%E7%94%A8%E6%88%B7%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B7%BB%E5%8A%A0%E8%AF%8D%E5%85%B8%E3%80%82)

对应的英文站点也是如此

**Comment by tianheg** [comment]
另一个问题：

英文站点的部分页面不是英文

**Comment by crimx** [comment]
墙内有的运营商屏蔽了 Cloudflare CDN，看看是不是这个问题。

> 英文站点的部分页面不是英文

不太想翻译了，所以开头写着“Help translate this page to English.”。

**Comment by tianheg** [comment]
不好意思，是我的错，我自以为这是自动翻译的












一大加贝
***@***.***

**Comment by tianheg** [comment]
不是这个问题。

链接在仓库访问时，的确是这个链接：

```
https://github.com/crimx/ext-saladict/blob/dev/CONTRIBUTING-zh.md
```

但在网页端却是：

```
https://github.com/crimx/ext-saladict/blob/dev/CONTRIBUTING-zh.html
```

**Comment by crimx** [comment]
啊明白了，这个是 vuepress 导致的，我看看怎么处理。
